name: 'Get Severity Level'
description: 'Gets the severity level of a vulnerability found by checkov, docs.prismacloud.io/...'
author: 'https://github.com/erikbjo'

inputs:
  LINKS:
    description: 'List of links to check'
    required: true

  FAIL_ON_LEVEL:
    description: 'Fail if severity level is equal or higher than this'
    required: true

runs:
  using: 'composite'
  steps:
    - name: 'Get Severity Levels'
      id: get_severity_level
      shell: bash
      env:
        LINKS: ${{ inputs.LINKS }}
        FAIL_ON_LEVEL: ${{ inputs.FAIL_ON_LEVEL }}
      run: |
        chmod +x .github/actions/getseveritylevel/checkseveritylevels.sh
        ./.github/actions/getseveritylevel/checkseveritylevels.sh $LINKS $FAIL_ON_LEVEL
