name: 'Setup Terraform with Azure'
description: 'Setup Terraform with Azure'

runs:
  using: 'composite'
  steps:
    - name: 'Do something'
      shell: bash
      id: do_something
      run: echo "Doing something"