name: 'Check Severity Level'
description: 'Compares the severity levels of checkov results to a given severity level.'
author: 'https://github.com/erikbjo'

inputs:
  LINKS:
    description: 'List of links to check, seperated by a comma.'
    required: true

  FAIL_ON_LEVEL:
    description: 'Fail if severity level is equal or higher than this. Ex: LOW, MEDIUM, HIGH'
    required: true

runs:
  using: 'composite'
  steps:
    - name: 'Check Severity Levels'
      id: check_severity_level
      shell: bash
      env:
        LINKS: ${{ inputs.LINKS }}
        FAIL_ON_LEVEL: ${{ inputs.FAIL_ON_LEVEL }}
      run: |
        chmod +x .github/actions/checkseveritylevel/checkseveritylevels.sh
        ./.github/actions/checkseveritylevel/checkseveritylevels.sh $LINKS $FAIL_ON_LEVEL
