name: 'destroy'
on:
  workflow_dispatch:

env:
  WORKING_DIR: 'deployments'
  WORKSPACE: ${{ github.ref == 'refs/heads/main' && 'prod' || github.ref_name }}
  TF_VAR_subscription_id: ${{ secrets.SUBSCRIPTION_ID }}
  TF_VAR_mssql_administrator_login: ${{ secrets.MSSQL_ADMINISTRATOR_LOGIN }}
  TF_VAR_mssql_administrator_login_password: ${{ secrets.MSSQL_ADMINISTRATOR_LOGIN_PASSWORD }}

jobs:
  destroy:
    runs-on: ubuntu-latest
    name: 'destroy'
    steps:
      - name: 'Checkout'
        id: checkout
        uses: actions/checkout@v4.1.7

      - name: 'Setup Terraform with Azure credentials'
        uses: './.github/actions/tfsetup'
        with:
          AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
          WORKSPACE: ${{ env.WORKSPACE }}
          WORKING_DIR: ${{ env.WORKING_DIR }}

      - name: 'Terraform destroy'
        id: destroy
        run: terraform destroy -auto-approve
        working-directory: ${{ env.WORKING_DIR }}