name: 'destroy'
on:
  workflow_dispatch:
    inputs:
      workspace:
        description: 'Workspace to destroy'
        required: true
        default: 'dev/stage/prod'

env:
  WORKING_DIR: 'deployments'
  WORKSPACE: ${{ inputs.workspace }}
  TF_VAR_subscription_id: ${{ secrets.SUBSCRIPTION_ID }}

jobs:
  destroy:
    runs-on: ubuntu-latest
    name: 'destroy'
    steps:
      - name: 'Checkout'
        id: checkout
        uses: actions/checkout@v4.1.7

      - name: 'Setup Terraform with Azure credentials'
        uses: './.github/actions/tfsetup'
        with:
          AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
          WORKSPACE: ${{ github.workflow }}
          WORKING_DIR: ${{ env.WORKING_DIR }}

      - name: 'Terraform destroy'
        id: destroy
        run: terraform destroy -auto-approve
        working-directory: ${{ env.WORKING_DIR }}