name: 'dev'
on:
  workflow_dispatch:

  push:
    branches:
      - dev
    paths-ignore:
      - '*.md'
      - '.gitignore'
      - '*.yml'

permissions:
  contents: read
  pull-requests: read

env:
  TF_VAR_subscription_id: ${{ secrets.SUBSCRIPTION_ID }}
  WORKING_DIR: 'deployments'
  GH_TOKEN: ${{ github.token }}

jobs:
  validate:
    runs-on: ubuntu-latest
    name: 'validate'
    steps:
      - name: 'Checkout'
        id: checkout
        uses: actions/checkout@v4.1.7

      - name: 'Setup Terraform with Azure credentials'
        id: setup
        uses: './.github/actions/tfsetup'
        with:
          AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
          WORKSPACE: ${{ github.workflow }}

      - name: 'Checkov with severity level'
        id: checkov
        uses: './.github/actions/checkovwithseveritylevel'
        with:
          WORKING_DIR: ${{ env.WORKING_DIR }}
          FAIL_ON_LEVEL: 'HIGH'

      # TODO: Step for tfsec scan

      - name: 'Terraform plan'
        id: plan
        run: terraform plan -out=tfplan

      - name: 'Save tfplan'
        uses: actions/cache/save@v4.1.2
        with:
          path: tfplan
          key: tfplan-${{ github.sha }}

  apply:
    needs: validate
    runs-on: ubuntu-latest
    name: 'apply'
    environment: 'dev'
    steps:
      - name: 'Checkout'
        id: checkout
        uses: actions/checkout@v4.1.7

      - name: 'Setup Terraform with Azure credentials'
        id: setup
        uses: './.github/actions/tfsetup'
        with:
          AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
          WORKSPACE: ${{ github.workflow }}

      - name: Restore cached source
        uses: actions/cache/restore@v4.1.2
        with:
          path: tfplan
          key: tfplan-${{ github.sha }}

      - name: 'Terraform apply'
        id: apply
        run: terraform apply -auto-approve tfplan

  # Eventual job for testing the infrastructure