name: 'dev'
on:
  workflow_dispatch:

  pull_request:
    branches:
      - dev
    paths-ignore:
      - '*.md'
      - '.gitignore'
      - '*.yml'
    types:
      - closed

jobs:
  validate:
    runs-on: ubuntu-latest
    name: 'validate'
    env:
      SUBSCRIPTION_ID: ${{ secrets.SUBSCRIPTION_ID }}
    steps:
      - name: 'Checkout'
        id: checkout
        uses: actions/checkout@v4.1.7

      - uses: './.github/actions/tfsetup'
        with:
          AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}

      - name: 'Terraform plan'
        id: plan
        run: terraform plan -out=tfplan

      - name: 'Checkov scan'
        id: checkov
        uses: bridgecrewio/checkov-action@master
        with:
          directory: ${{ env.WORKING_DIR }}
          output_format: 'github_failed_only'
          soft_fail: true
          download_external_modules: true
          output_file_path: 'checkov-report,'

      - name: 'ls -la'
        id: ls
        shell: bash
        run: ls -la

      - name: 'cat checkov'
        id: cat
        shell: bash
        run: cat checkov-report