name: 'dev'
on:
  workflow_dispatch:

  pull_request:
    branches:
      - dev
    paths-ignore:
      - '*.md'
      - '.gitignore'
      - '*.yml'
    types:
      - closed

permissions:
  contents: read
  pull-requests: read

env:
  TF_VAR_subscription_id: ${{ secrets.SUBSCRIPTION_ID }}
  WORKING_DIR: '.'
  GH_TOKEN: ${{ github.token }}

jobs:
  validate:
    runs-on: ubuntu-latest
    name: 'validate'
    steps:
      - name: 'Checkout'
        id: checkout
        uses: actions/checkout@v4.1.7

      - name: 'Setup Terraform with Azure credentials'
        id: setup
        uses: './.github/actions/tfsetup'
        with:
          AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
          WORKSPACE: ${{ github.workflow }}

      - name: 'Checkov with severity level'
        id: checkov
        uses: './.github/actions/checkovwithseveritylevel'
        with:
          WORKING_DIR: ${{ env.WORKING_DIR }}
          FAIL_ON_LEVEL: 'HIGH'

      # TODO: Step for tfsec scan

      - name: 'Terraform plan'
        id: plan
        run: terraform plan -out=tfplan

      # TODO: Step for uploading and accepting the plan, before new job for apply

  apply:
    needs: validate
    runs-on: ubuntu-latest
    name: 'apply'
    steps:
      - name: 'Checkout'
        id: checkout
        uses: actions/checkout@v4.1.7

      - name: 'Setup Terraform with Azure credentials'
        id: setup
        uses: './.github/actions/tfsetup'
        with:
          AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
          WORKSPACE: ${{ github.workflow }}

      # TODO: Download tfplan from validate job

      - name: 'Terraform apply'
        id: apply
        run: terraform apply -auto-approve tfplan

  # Eventual job for testing the infrastructure