name: 'dev'
on:
  workflow_dispatch:

  pull_request:
    branches:
      - dev
    paths-ignore:
      - '*.md'
      - '.gitignore'
      - '*.yml'
    types:
      - closed

permissions:
  contents: read
  pull-requests: read

env:
  TF_VAR_subscription_id: ${{ secrets.SUBSCRIPTION_ID }}
  WORKING_DIR: '.'

jobs:
  validate:
    runs-on: ubuntu-latest
    name: 'validate'
    steps:
      - name: 'Checkout'
        id: checkout
        uses: actions/checkout@v4.1.7

      - uses: './.github/actions/tfsetup'
        with:
          AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}

      - name: 'Terraform plan'
        id: plan
        run: terraform plan -out=tfplan

      - name: 'Checkov scan'
        id: checkov
        uses: bridgecrewio/checkov-action@master
        with:
          directory: ${{ env.WORKING_DIR }}
          output_format: 'github_failed_only'
          download_external_modules: true
          # output_file_path: 'checkov-report,'
          soft_fail_on: 'LOW'
