name: 'dev'
on:
  workflow_dispatch:

  pull_request:
    branches:
      - dev
    paths-ignore:
      - '*.md'
      - '.gitignore'
      - '*.yml'
    types:
      - closed

jobs:
  validate:
    runs-on: ubuntu-latest
    name: 'validate'
    steps:
      - name: 'Checkout'
        id: checkout
        uses: actions/checkout@v4.1.7

      - name: 'Do something'
        run: echo "Do something"

      - name: 'ls -la'
        run: ls -la .github

      - name: 'ls -la 2'
        run: ls -la .github/actions

      - uses: './.github/actions/tfsetup'