name: 'dev'
on:
  workflow_dispatch:

  pull_request:
    branches:
      - dev
    paths-ignore:
      - '*.md'
      - '.gitignore'
      - '*.yml'
    types:
      - closed

jobs:
  validate:
    runs-on: ubuntu-latest
    name: 'validate'
    steps:
      - name: 'Checkout'
        id: checkout
        uses: actions/checkout@v4.1.7
        with:
          sparse-checkout: .github/actions
          path: actions

      - uses: erikbjo/erbj-oppg2/.github/actions/tfsetup
        with:
          terraform_workspace: 'dev'
  deploy: