name: 'stage'
on:
  workflow_dispatch:

  pull_request:
    branches:
      - stage
    paths-ignore:
      - '*.md'
      - '.gitignore'
      - '*.yml'
    types:
      - closed

permissions:
  contents: read
  pull-requests: read

env:
  TF_VAR_subscription_id: ${{ secrets.SUBSCRIPTION_ID }}
  WORKING_DIR: 'deployments'
  GH_TOKEN: ${{ github.token }}
  WORKSPACE: ${{ github.workflow }}

jobs:
  validate:
    runs-on: ubuntu-latest
    name: 'validate'
    steps:
      - name: 'Checkout'
        id: checkout
        uses: actions/checkout@v4.1.7

  apply:
    runs-on: ubuntu-latest
    name: 'apply'
    steps:
      - name: 'Checkout'
        id: checkout
        uses: actions/checkout@v4.1.7